name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - devtest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Configure AWS region
      run: aws configure set region ${{ secrets.AWS_REGION }}
      
    - name: Deploy to Elastic Beanstalk
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws elasticbeanstalk update-environment --environment-id e-sgmem2imph --version-label 13.0

  # Add more steps if needed, such as running tests, etc.
